In [35]:
import numpy as np

english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,np.nan,60])
chinese_score = np.array([65,90,82,72,66,77])


In [36]:
#1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?

eng_mean = np.mean(english_score)
math_mean = np.nanmean(math_score)
ch_mean = np.mean(chinese_score)
print("英文平均：",eng_mean)
print("數學平均：",math_mean)
print("國文平均：",ch_mean)

eng_max = np.amax(english_score)
math_max = np.nanmax(math_score)
ch_max = np.amax(chinese_score)

print("英文最高分：",eng_max)
print("數學最高分：",math_max)
print("國文最高分：",ch_max)

eng_min = np.amin(english_score)
math_min = np.nanmin(math_score)
ch_min = np.amin(chinese_score)

print("英文最低分：",eng_min)
print("數學最低分：",math_min)
print("國文最低分：",ch_min)

eng_sd = np.std(english_score)
math_sd = np.nanstd(math_score)
ch_sd = np.std(chinese_score)

print("英文標準差：",eng_sd)
print("數學標準差：",math_sd)
print("國文標準差：",ch_sd)

英文平均： 67.16666666666667
數學平均： 66.6
國文平均： 75.33333333333333
英文最高分： 89
數學最高分： 85.0
國文最高分： 90
英文最低分： 48
數學最低分： 60.0
國文最低分： 65
英文標準差： 13.433995020924426
數學標準差： 9.707728879609279
國文標準差： 8.825468196582484


In [37]:
#2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?
math_score_nw = np.array([60,85,60,68,55,60])
math_mean = np.nanmean(math_score_nw)
math_max = np.nanmax(math_score_nw)
math_min = np.nanmin(math_score_nw)
math_sd = np.nanstd(math_score_nw)
print(math_mean,math_max, math_min, math_sd)

64.66666666666667 85 55 9.860132971832694


In [50]:
#3. 用補考後資料找出與國文成績相關係數最高的學科?
ch_en = np.array([chinese_score, english_score])
ch_en
print(np.corrcoef(ch_en))

ch_ma = np.array([chinese_score, math_score_nw])
print(np.corrcoef(ch_ma))
print(np.fmax(np.corrcoef(ch_en), np.corrcoef(ch_ma)))


[[1.         0.97792828]
 [0.97792828 1.        ]]
[[1.         0.74056803]
 [0.74056803 1.        ]]
[[1.         0.97792828]
 [0.97792828 1.        ]]
